### ISSUE TITLE
Add `register_database` method

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-catalogprovider-glue#3]
I would like to register a single database and not the entire glue catalog

**Comment by timvw** [comment]
The following functions are already available:

    /// Register all tables in the given glue database
    pub async fn register_tables(&mut self, database: &str) -> Result<Vec<Result<()>>> {

    /// Register the table with the given database and table name
    pub async fn register_table(&mut self, database: &str, table: &str) -> Result<()> {

**Comment by matthewmturner** [comment]
@timvw Ah sry I should have looked at the signatures closer. Thanks!

**Comment by timvw** [comment]
You're welcome ;)
